-- Generated by nwg-displays on 2026-08-09 at 11:19:00. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "0x611",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@119.97999999999999",
    position = "1080x121",
    scale = 1.0,
    transform = 2
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@159.98000000000002",
    position = "1080x1201",
    scale = 1.0
})
