# use zsh as default
set -g default-shell /bin/zsh

# enable 256-color and true-color (24-bit) support
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*245col*:Tc"

# General
set -g set-clipboard on
set -g mouse on

# Refresh tmux config with r
unbind r
bind r source-file ~/.tmux.conf

# CPU and memory info
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'

# Style
gray_light="#C0CAF5"
gray_medium="#414868"
gray_dark="#414868"
green_soft="#9ECE6A"
blue_muted="#7AA2F7"
cyan_soft="#7DCFFF"

set -g status-position top
set -g status-style "fg=${gray_light},bg=default"
set -g status-left "#[fg=${green_soft},bold] #S #[fg=${gray_light},nobold] | "
set -g status-right " #{cpu}  #{mem}"
set -g window-status-current-format "#[fg=${cyan_soft},bold]  #[underscore]#I:#W"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
